# Generated by Django 5.0.1 on 2026-07-22 20:41

import django.core.validators
import django.db.models.deletion
import licenses.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_number', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(db_index=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to=licenses.models.certificate_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('status', models.CharField(choices=[('compliant', 'Compliant'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('pending', 'Pending Verification')], db_index=True, default='pending', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reminder_30_sent', models.BooleanField(default=False)),
                ('reminder_15_sent', models.BooleanField(default=False)),
                ('reminder_7_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_licenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'licenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LicenseAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('deleted', 'Deleted')], max_length=20)),
                ('changes', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='licenses.license')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'license_audits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['status', 'expiry_date'], name='licenses_status_30793e_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['agent'], name='licenses_agent_i_afeaf9_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['license_number'], name='licenses_license_09b588_idx'),
        ),
    ]
